## 0.1 Importing Libraries

In [1]:
# Import libraries 
import pandas as pd
import numpy as np
import os

## Importing data

In [2]:
df= pd.read_csv(r"C:\Users\You\Documents\Instacart Basket Analysis\02 Data\Original Data", index_col = False)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\You\\Documents\\Instacart Basket Analysis\\02 Data\\Original Data'

In [1]:
df= pd.read_csv(r"C:\Users\You\One Drive - Universitat de Barcelona\Instacart Basket Analysis\02 Data\Original Data", index_col = False)

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [3]:
df= pd.read_csv(r"C:\Users\You\One Drive - Universitat de Barcelona\Instacart Basket Analysis\02 Data\Original Data", index_col = False)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\You\\One Drive - Universitat de Barcelona\\Instacart Basket Analysis\\02 Data\\Original Data'

In [4]:
df= pd.read_csv(r"C:One Drive - Universitat de Barcelona\Instacart Basket Analysis\02 Data\Original Data", index_col = False)

FileNotFoundError: [Errno 2] No such file or directory: 'C:One Drive - Universitat de Barcelona\\Instacart Basket Analysis\\02 Data\\Original Data'

In [10]:
import glob

In [12]:
# Importing orders file 
df =  pd.read_csv(r"C:\Users\user\OneDrive - Universitat de Barcelona\Instacart Basket Analysis\02 Data\Original Data\orders.csv", index_col=False)

In [14]:
project_folder = r"C:\Users\user\OneDrive - Universitat de Barcelona\Instacart Basket Analysis"

In [16]:
df = pd.read_csv(os.path.join(project_folder,"02 Data","Original Data","orders.csv"),index_col = False)

NameError: name 'os' is not defined

In [17]:
import os

In [18]:
df = pd.read_csv(os.path.join(project_folder,"02 Data","Original Data","orders.csv"),index_col = False)

In [19]:
print(df.head())

   order_id  user_id eval_set  order_number  order_dow  order_hour_of_day  \
0   2539329        1    prior             1          2                  8
1   2398795        1    prior             2          3                  7
2    473747        1    prior             3          3                 12
3   2254736        1    prior             4          4                  7
4    431534        1    prior             5          4                 15

   days_since_prior_order
0                     NaN
1                    15.0
2                    21.0
3                    29.0
4                    28.0

In [1]:
df=pd.read_csv(r"C:\Users\user\OneDrive - Universitat de Barcelona\Instacart Basket Analysis\02 Data\Original Data\orders.csv",index_col= False)

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\user\OneDrive - Universitat de Barcelona\Instacart Basket Analysis\02 Data\Original Data\orders.csv",index_col= False)

In [4]:
path = r"C:\Users\user\OneDrive - Universitat de Barcelona\Instacart Basket Analysis"

In [5]:
path

'C:\\Users\\user\\OneDrive - Universitat de Barcelona\\Instacart Basket Analysis'

In [7]:
import os

In [8]:
df=pd.read_csv(os.path.join(path, "02 Data","Original Data", "orders.csv"),index_col= False)

In [10]:
df.head(30)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
6,550135,1,prior,7,1,9,20.0
7,3108588,1,prior,8,1,14,14.0
8,2295261,1,prior,9,1,16,0.0
9,2550362,1,prior,10,4,8,30.0
10,1187899,1,train,11,4,8,14.0
11,2168274,2,prior,1,2,11,NaN
12,1501582,2,prior,2,5,10,10.0
13,1901567,2,prior,3,1,10,3.0
14,738281,2,prior,4,2,10,8.0
15,1673511,2,prior,5,3,11,8.0
16,1199898,2,prior,6,2,9,13.0
17,3194192,2,prior,7,2,12,14.0
18,788338,2,prior,8,1,15,27.0
19,1718559,2,prior,9,2,9,8.0
20,1447487,2,prior,10,1,11,6.0
21,1402090,2,prior,11,1,10,30.0
22,3186735,2,prior,12,1,9,28.0
23,3268552,2,prior,13,4,11,30.0
24,839880,2,prior,14,3,10,13.0
25,1492625,2,train,15,1,11,30.0
26,1374495,3,prior,1,1,14,NaN
27,444309,3,prior,2,3,19,9.0
28,3002854,3,prior,3,3,16,21.0
29,2037211,3,prior,4,2,18,20.0

In [10]:
df.head(30)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
6,550135,1,prior,7,1,9,20.0
7,3108588,1,prior,8,1,14,14.0
8,2295261,1,prior,9,1,16,0.0
9,2550362,1,prior,10,4,8,30.0
10,1187899,1,train,11,4,8,14.0
11,2168274,2,prior,1,2,11,NaN
12,1501582,2,prior,2,5,10,10.0
13,1901567,2,prior,3,1,10,3.0
14,738281,2,prior,4,2,10,8.0
15,1673511,2,prior,5,3,11,8.0
16,1199898,2,prior,6,2,9,13.0
17,3194192,2,prior,7,2,12,14.0
18,788338,2,prior,8,1,15,27.0
19,1718559,2,prior,9,2,9,8.0
20,1447487,2,prior,10,1,11,6.0
21,1402090,2,prior,11,1,10,30.0
22,3186735,2,prior,12,1,9,28.0
23,3268552,2,prior,13,4,11,30.0
24,839880,2,prior,14,3,10,13.0
25,1492625,2,train,15,1,11,30.0
26,1374495,3,prior,1,1,14,NaN
27,444309,3,prior,2,3,19,9.0
28,3002854,3,prior,3,3,16,21.0
29,2037211,3,prior,4,2,18,20.0

In [11]:
df.tail()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [12]:
df.shape

(3421083, 7)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                object
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), object(1)
memory usage: 182.7+ MB

In [14]:
df.dtypes

order_id                    int64
user_id                     int64
eval_set                   object
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [15]:
df.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='object')

In [16]:
df.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [17]:
df = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'orders.csv'), nrows=1000)

In [18]:
vars_list = ['order_id', 'user_id', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order']

In [19]:
df = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'orders.csv'), usecols = vars_list)

In [20]:
vars list

SyntaxError: invalid syntax (2841437221.py, line 1)

In [21]:
vars_list

['order_id',
 'user_id',
 'order_number',
 'order_dow',
 'order_hour_of_day',
 'days_since_prior_order']

In [22]:
df.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0