In [1]:
# Importing libraries

In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
# Import your main ords_prods_merge dataframe. Call it ords_prods_merge

In [4]:
path= r'C:\Users\user\OneDrive - Universitat de Barcelona\Instacart Basket Analysis'

In [5]:
ords_prods_merge= pd.read_pickle(os.path.join(path,'02 Data','Prepared Data','ords_prods_merge_new.pkl'))

In [6]:
# Create a subset called df of the first one million entries

In [7]:
df = ords_prods_merge[:1000000]

In [8]:
df.shape

(1000000, 23)

In [9]:
df.head()

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,...,product_name,aisle_id,department_id,prices,merge_status,price_range_loc,busiest day,busiest days,busiest hours,busiest_period_of_day
0,0,2539329,1,prior,1,2,8,NaN,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,Average orders
1,0,2539329,1,prior,1,2,8,NaN,14084,2,...,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders,Average orders
2,0,2539329,1,prior,1,2,8,NaN,12427,3,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders
3,0,2539329,1,prior,1,2,8,NaN,26088,4,...,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders
4,0,2539329,1,prior,1,2,8,NaN,26405,5,...,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders

In [10]:
df.groupby('product_name')

In [11]:
# Split the data into groups based on “department_id.”
# Apply the agg() function to each group to obtain the mean values for the “order_number” column

In [12]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                14.800024
2                17.091743
3                17.913544
4                17.893092
5                15.214270
6                15.382135
7                17.694027
8                16.458105
9                15.957363
10               20.091818
11               16.482026
12               15.615061
13               16.484023
14               17.524632
15               15.691875
16               18.014071
17               16.150593
18               19.602850
19               17.631340
20               17.138607
21               21.956893

In [13]:
df.groupby('department_id')['order_number'].mean()

department_id
1     14.800024
2     17.091743
3     17.913544
4     17.893092
5     15.214270
6     15.382135
7     17.694027
8     16.458105
9     15.957363
10    20.091818
11    16.482026
12    15.615061
13    16.484023
14    17.524632
15    15.691875
16    18.014071
17    16.150593
18    19.602850
19    17.631340
20    17.138607
21    21.956893
Name: order_number, dtype: float64

In [14]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                14.800024   1  99
2                17.091743   1  98
3                17.913544   1  99
4                17.893092   1  99
5                15.214270   1  99
6                15.382135   1  99
7                17.694027   1  99
8                16.458105   1  91
9                15.957363   1  99
10               20.091818   1  99
11               16.482026   1  99
12               15.615061   1  99
13               16.484023   1  99
14               17.524632   1  99
15               15.691875   1  99
16               18.014071   1  99
17               16.150593   1  99
18               19.602850   1  99
19               17.631340   1  99
20               17.138607   1  99
21               21.956893   1  97

In [15]:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

C:\Users\user\AppData\Local\Temp\ipykernel_15552\1681540670.py:1: FutureWarning: The provided callable <function max at 0x000002A0499205E0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [16]:
ords_prods_merge.head()

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,...,aisle_id,department_id,prices,merge_status,price_range_loc,busiest day,busiest days,busiest hours,busiest_period_of_day,max_order
0,0,2539329,1,prior,1,2,8,NaN,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
1,0,2539329,1,prior,1,2,8,NaN,14084,2,...,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
2,0,2539329,1,prior,1,2,8,NaN,12427,3,...,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
3,0,2539329,1,prior,1,2,8,NaN,26088,4,...,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
4,0,2539329,1,prior,1,2,8,NaN,26405,5,...,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders,10

In [17]:
ords_prods_merge.head(100)

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,...,aisle_id,department_id,prices,merge_status,price_range_loc,busiest day,busiest days,busiest hours,busiest_period_of_day,max_order
0,0,2539329,1,prior,1,2,8,NaN,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
1,0,2539329,1,prior,1,2,8,NaN,14084,2,...,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
2,0,2539329,1,prior,1,2,8,NaN,12427,3,...,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
3,0,2539329,1,prior,1,2,8,NaN,26088,4,...,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
4,0,2539329,1,prior,1,2,8,NaN,26405,5,...,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,14,738281,2,prior,4,2,10,8.0,21150,13,...,38,1,5.9,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
96,15,1673511,2,prior,5,3,11,8.0,47144,1,...,91,16,14.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,14
97,15,1673511,2,prior,5,3,11,8.0,5322,2,...,3,19,2.9,both,Low-range product,Regularly busy,Least busy,Most orders,Most orders,14
98,15,1673511,2,prior,5,3,11,8.0,17224,3,...,3,19,1.6,both,Low-range product,Regularly busy,Least busy,Most orders,Most orders,14
99,15,1673511,2,prior,5,3,11,8.0,38656,4,...,3,19,3.4,both,Low-range product,Regularly busy,Least busy,Most orders,Most orders,14

In [18]:
pd.options.display.max_rows = None

In [19]:
ords_prods_merge.head(100)

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,...,aisle_id,department_id,prices,merge_status,price_range_loc,busiest day,busiest days,busiest hours,busiest_period_of_day,max_order
0,0,2539329,1,prior,1,2,8,NaN,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
1,0,2539329,1,prior,1,2,8,NaN,14084,2,...,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
2,0,2539329,1,prior,1,2,8,NaN,12427,3,...,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
3,0,2539329,1,prior,1,2,8,NaN,26088,4,...,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
4,0,2539329,1,prior,1,2,8,NaN,26405,5,...,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
5,1,2398795,1,prior,2,3,7,15.0,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Average orders,Average orders,10
6,1,2398795,1,prior,2,3,7,15.0,10258,2,...,117,19,3.0,both,Low-range product,Regularly busy,Least busy,Average orders,Average orders,10
7,1,2398795,1,prior,2,3,7,15.0,12427,3,...,23,19,4.4,both,Low-range product,Regularly busy,Least busy,Average orders,Average orders,10
8,1,2398795,1,prior,2,3,7,15.0,13176,4,...,24,4,10.3,both,Mid-range product,Regularly busy,Least busy,Average orders,Average orders,10
9,1,2398795,1,prior,2,3,7,15.0,26088,5,...,23,19,4.7,both,Low-range product,Regularly busy,Least busy,Average orders,Average orders,10
10,1,2398795,1,prior,2,3,7,15.0,13032,6,...,121,14,4.0,both,Low-range product,Regularly busy,Least busy,Average orders,Average orders,10
11,2,473747,1,prior,3,3,12,21.0,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Average orders,Average orders,10
12,2,473747,1,prior,3,3,12,21.0,12427,2,...,23,19,4.4,both,Low-range product,Regularly busy,Least busy,Average orders,Average orders,10
13,2,473747,1,prior,3,3,12,21.0,10258,3,...,117,19,3.0,both,Low-range product,Regularly busy,Least busy,Average orders,Average orders,10
14,2,473747,1,prior,3,3,12,21.0,25133,4,...,21,16,8.6,both,Mid-range product,Regularly busy,Least busy,Average orders,Average orders,10
15,2,473747,1,prior,3,3,12,21.0,30450,5,...,88,13,3.2,both,Low-range product,Regularly busy,Least busy,Average orders,Average orders,10
16,3,2254736,1,prior,4,4,7,29.0,196,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Average orders,Average orders,10
17,3,2254736,1,prior,4,4,7,29.0,12427,2,...,23,19,4.4,both,Low-range product,Least busy,Least busy,Average orders,Average orders,10
18,3,2254736,1,prior,4,4,7,29.0,10258,3,...,117,19,3.0,both,Low-range product,Least busy,Least busy,Average orders,Average orders,10
19,3,2254736,1,prior,4,4,7,29.0,25133,4,...,21,16,8.6,both,Mid-range product,Least busy,Least busy,Average orders,Average orders,10
20,3,2254736,1,prior,4,4,7,29.0,26405,5,...,54,17,1.0,both,Low-range product,Least busy,Least busy,Average orders,Average orders,10
21,4,431534,1,prior,5,4,15,28.0,196,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,10
22,4,431534,1,prior,5,4,15,28.0,12427,2,...,23,19,4.4,both,Low-range product,Least busy,Least busy,Most orders,Most orders,10
23,4,431534,1,prior,5,4,15,28.0,10258,3,...,117,19,3.0,both,Low-range product,Least busy,Least busy,Most orders,Most orders,10
24,4,431534,1,prior,5,4,15,28.0,25133,4,...,21,16,8.6,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,10
25,4,431534,1,prior,5,4,15,28.0,10326,5,...,24,4,2.7,both,Low-range product,Least busy,Least busy,Most orders,Most orders,10
26,4,431534,1,prior,5,4,15,28.0,17122,6,...,24,4,14.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,10
27,4,431534,1,prior,5,4,15,28.0,41787,7,...,24,4,5.0,both,NaN,Least busy,Least busy,Most orders,Most orders,10
28,4,431534,1,prior,5,4,15,28.0,13176,8,...,24,4,10.3,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,10
29,5,3367565,1,prior,6,2,7,19.0,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
30,5,3367565,1,prior,6,2,7,19.0,12427,2,...,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
31,5,3367565,1,prior,6,2,7,19.0,10258,3,...,117,19,3.0,both,Low-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
32,5,3367565,1,prior,6,2,7,19.0,25133,4,...,21,16,8.6,both,Mid-range product,Regularly busy,Regularly busy,Average orders,Average orders,10
33,6,550135,1,prior,7,1,9,20.0,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,Average orders,10
34,6,550135,1,prior,7,1,9,20.0,10258,2,...,117,19,3.0,both,Low-range product,Regularly busy,Busiest days,Average orders,Average orders,10
35,6,550135,1,prior,7,1,9,20.0,12427,3,...,23,19,4.4,both,Low-range product,Regularly busy,Busiest days,Average orders,Average orders,10
36,6,550135,1,prior,7,1,9,20.0,25133,4,...,21,16,8.6,both,Mid-range product,Regularly busy,Busiest days,Average orders,Average orders,10
37,6,550135,1,prior,7,1,9,20.0,13032,5,...,121,14,4.0,both,Low-range product,Regularly busy,Busiest days,Average orders,Average orders,10
38,7,3108588,1,prior,8,1,14,14.0,12427,1,...,23,19,4.4,both,Low-range product,Regularly busy,Busiest days,Most orders,Most orders,10
39,7,3108588,1,prior,8,1,14,14.0,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,Most orders,10
40,7,3108588,1,prior,8,1,14,14.0,10258,3,...,117,19,3.0,both,Low-range product,Regularly busy,Busiest days,Most orders,Most orders,10
41,7,3108588,1,prior,8,1,14,14.0,25133,4,...,21,16,8.6,both,Mid-range product,Regularly busy,Busiest days,Most orders,Most orders,10
42,7,3108588,1,prior,8,1,14,14.0,46149,5,...,77,7,13.4,both,Mid-range product,Regularly busy,Busiest days,Most orders,Most orders,10
43,7,3108588,1,prior,8,1,14,14.0,49235,6,...,53,16,1.8,both,Low-range product,Regularly busy,Busiest days,Most orders,Most orders,10
44,8,2295261,1,prior,9,1,16,0.0,49235,1,...,53,16,1.8,both,Low-range product,Regularly busy,Busiest days,Average orders,Average orders,10
45,8,2295261,1,prior,9,1,16,0.0,46149,2,...,77,7,13.4,both,Mid-range product,Regularly busy,Busiest days,Average orders,Average orders,10
46,8,2295261,1,prior,9,1,16,0.0,25133,3,...,21,16,8.6,both,Mid-range product,Regularly busy,Busiest days,Average orders,Average orders,10
47,8,2295261,1,prior,9,1,16,0.0,196,4,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,Average orders,10
48,8,2295261,1,prior,9,1,16,0.0,10258,5,...,117,19,3.0,both,Low-range product,Regularly busy,Busiest days,Average orders,Average orders,10
49,8,2295261,1,prior,9,1,16,0.0,12427,6,...,23,19,4.4,both,Low-range product,Regularly busy,Busiest days,Average orders,Average orders,10
50,9,2550362,1,prior,10,4,8,30.0,196,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Average orders,Average orders,10
51,9,2550362,1,prior,10,4,8,30.0,46149,2,...,77,7,13.4,both,Mid-range product,Least busy,Least busy,Average orders,Average orders,10
52,9,2550362,1,prior,10,4,8,30.0,39657,3,...,45,19,6.8,both,Mid-range product,Least busy,Least busy,Average orders,Average orders,10
53,9,2550362,1,prior,10,4,8,30.0,38928,4,...,120,16,12.6,both,Mid-range product,Least busy,Least busy,Average orders,Average orders,10
54,9,2550362,1,prior,10,4,8,30.0,25133,5,...,21,16,8.6,both,Mid-range product,Least busy,Least busy,Average orders,Average orders,10
55,9,2550362,1,prior,10,4,8,30.0,10258,6,...,117,19,3.0,both,Low-range product,Least busy,Least busy,Average orders,Average orders,10
56,9,2550362,1,prior,10,4,8,30.0,35951,7,...,91,16,1.3,both,Low-range product,Least busy,Least busy,Average orders,Average orders,10
57,9,2550362,1,prior,10,4,8,30.0,13032,8,...,121,14,4.0,both,Low-range product,Least busy,Least busy,Average orders,Average orders,10
58,9,2550362,1,prior,10,4,8,30.0,12427,9,...,23,19,4.4,both,Low-range product,Least busy,Least busy,Average orders,Average orders,10
59,11,2168274,2,prior,1,2,11,NaN,32792,1,...,23,19,5.2,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
60,11,2168274,2,prior,1,2,11,NaN,47766,2,...,24,4,6.3,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
61,11,2168274,2,prior,1,2,11,NaN,20574,3,...,96,20,2.3,both,Low-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
62,11,2168274,2,prior,1,2,11,NaN,12000,4,...,72,13,10.9,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
63,11,2168274,2,prior,1,2,11,NaN,48110,5,...,78,19,2.7,both,Low-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
64,11,2168274,2,prior,1,2,11,NaN,22474,6,...,78,19,4.1,both,Low-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
65,11,2168274,2,prior,1,2,11,NaN,16589,7,...,107,19,5.0,both,NaN,Regularly busy,Regularly busy,Most orders,Most orders,14
66,11,2168274,2,prior,1,2,11,NaN,35917,8,...,98,7,9.4,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
67,11,2168274,2,prior,1,2,11,NaN,27344,9,...,96,20,14.8,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
68,11,2168274,2,prior,1,2,11,NaN,30489,10,...,67,20,7.5,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
69,11,2168274,2,prior,1,2,11,NaN,27966,11,...,123,4,4.4,both,Low-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
70,11,2168274,2,prior,1,2,11,NaN,13176,12,...,24,4,10.3,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
71,11,2168274,2,prior,1,2,11,NaN,45066,13,...,24,4,2.5,both,Low-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
72,12,1501582,2,prior,2,5,10,10.0,16797,1,...,24,4,1.3,both,Low-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
73,12,1501582,2,prior,2,5,10,10.0,47526,2,...,21,16,2.0,both,Low-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
74,12,1501582,2,prior,2,5,10,10.0,8479,3,...,78,19,3.5,both,Low-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
75,12,1501582,2,prior,2,5,10,10.0,47766,4,...,24,4,6.3,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
76,12,1501582,2,prior,2,5,10,10.0,19051,5,...,107,19,3.9,both,Low-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
77,12,1501582,2,prior,2,5,10,10.0,8138,6,...,67,20,2.0,both,Low-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
78,13,1901567,2,prior,3,1,10,3.0,47766,1,...,24,4,6.3,both,Mid-range product,Regularly busy,Busiest days,Most orders,Most orders,14
79,13,1901567,2,prior,3,1,10,3.0,32792,2,...,23,19,5.2,both,Mid-range product,Regularly busy,Busiest days,Most orders,Most orders,14
80,13,1901567,2,prior,3,1,10,3.0,20574,3,...,96,20,2.3,both,Low-range product,Regularly busy,Busiest days,Most orders,Most orders,14
81,13,1901567,2,prior,3,1,10,3.0,7781,4,...,21,16,6.6,both,Mid-range product,Regularly busy,Busiest days,Most orders,Most orders,14
82,13,1901567,2,prior,3,1,10,3.0,28874,5,...,1,20,6.2,both,Mid-range product,Regularly busy,Busiest days,Most orders,Most orders,14
83,14,738281,2,prior,4,2,10,8.0,49451,1,...,67,20,7.1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
84,14,738281,2,prior,4,2,10,8.0,32792,2,...,23,19,5.2,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
85,14,738281,2,prior,4,2,10,8.0,32139,3,...,67,20,7.5,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
86,14,738281,2,prior,4,2,10,8.0,34688,4,...,31,7,5.8,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
87,14,738281,2,prior,4,2,10,8.0,36735,5,...,96,20,8.9,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
88,14,738281,2,prior,4,2,10,8.0,37646,6,...,24,4,9.1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
89,14,738281,2,prior,4,2,10,8.0,22829,7,...,78,19,5.5,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
90,14,738281,2,prior,4,2,10,8.0,24852,8,...,24,4,12.3,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
91,14,738281,2,prior,4,2,10,8.0,47209,9,...,24,4,4.0,both,Low-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
92,14,738281,2,prior,4,2,10,8.0,33276,10,...,67,20,10.8,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
93,14,738281,2,prior,4,2,10,8.0,45613,11,...,38,1,12.6,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
94,14,738281,2,prior,4,2,10,8.0,9681,12,...,38,1,2.0,both,Low-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
95,14,738281,2,prior,4,2,10,8.0,21150,13,...,38,1,5.9,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
96,15,1673511,2,prior,5,3,11,8.0,47144,1,...,91,16,14.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,14
97,15,1673511,2,prior,5,3,11,8.0,5322,2,...,3,19,2.9,both,Low-range product,Regularly busy,Least busy,Most orders,Most orders,14
98,15,1673511,2,prior,5,3,11,8.0,17224,3,...,3,19,1.6,both,Low-range product,Regularly busy,Least busy,Most orders,Most orders,14
99,15,1673511,2,prior,5,3,11,8.0,38656,4,...,3,19,3.4,both,Low-range product,Regularly busy,Least busy,Most orders,Most orders,14

In [20]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [21]:

ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [22]:

ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [23]:
ords_prods_merge['loyalty_flag'].value_counts(dropna=False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [24]:
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             1
2         1      New customer             1
3         1      New customer             1
4         1      New customer             1
5         1      New customer             2
6         1      New customer             2
7         1      New customer             2
8         1      New customer             2
9         1      New customer             2
10        1      New customer             2
11        1      New customer             3
12        1      New customer             3
13        1      New customer             3
14        1      New customer             3
15        1      New customer             3
16        1      New customer             4
17        1      New customer             4
18        1      New customer             4
19        1      New customer             4
20        1      New customer             4
21        1      New customer             5
22        1      New customer             5
23        1      New customer             5
24        1      New customer             5
25        1      New customer             5
26        1      New customer             5
27        1      New customer             5
28        1      New customer             5
29        1      New customer             6
30        1      New customer             6
31        1      New customer             6
32        1      New customer             6
33        1      New customer             7
34        1      New customer             7
35        1      New customer             7
36        1      New customer             7
37        1      New customer             7
38        1      New customer             8
39        1      New customer             8
40        1      New customer             8
41        1      New customer             8
42        1      New customer             8
43        1      New customer             8
44        1      New customer             9
45        1      New customer             9
46        1      New customer             9
47        1      New customer             9
48        1      New customer             9
49        1      New customer             9
50        1      New customer            10
51        1      New customer            10
52        1      New customer            10
53        1      New customer            10
54        1      New customer            10
55        1      New customer            10
56        1      New customer            10
57        1      New customer            10
58        1      New customer            10
59        2  Regular customer             1

In [25]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge_final.pkl'))